// <auto-generated />
using System;
using CheckpointAPI.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CheckpointAPI.DataAccess.Migrations
{
    [DbContext(typeof(CheckpointDbContext))]
    [Migration("20260425143431_Week3_GameSeedData")]
    partial class Week3_GameSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CheckpointAPI.Entities.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GameName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("CheckpointAPI.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Developer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Publisher")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoverImageUrl = "https://picsum.photos/seed/eldenring/300/400",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "George R.R. Martin ile birlikte geliştirilen açık dünya aksiyon RPG. Lands Between'i keşfet, zorlu patronlarla savaş ve Elden Ring'i yeniden topla.",
                            Developer = "FromSoftware",
                            Publisher = "Bandai Namco",
                            Rating = 4.9000000000000004,
                            ReleaseYear = 2022,
                            ReviewCount = 0,
                            Title = "Elden Ring"
                        },
                        new
                        {
                            Id = 2,
                            CoverImageUrl = "https://picsum.photos/seed/cyberpunk/300/400",
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Night City'de geçen açık dünya aksiyon RPG. V olarak oyna ve efsanevi implant peşinde koş.",
                            Developer = "CD Projekt Red",
                            Publisher = "CD Projekt",
                            Rating = 4.2999999999999998,
                            ReleaseYear = 2020,
                            ReviewCount = 0,
                            Title = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = 3,
                            CoverImageUrl = "https://picsum.photos/seed/starfield/300/400",
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Constellation üyesi olarak yıldızlar arası keşfe çık. 1000'den fazla gezegende keşif ve macera.",
                            Developer = "Bethesda Game Studios",
                            Publisher = "Bethesda Softworks",
                            Rating = 3.8999999999999999,
                            ReleaseYear = 2023,
                            ReviewCount = 0,
                            Title = "Starfield"
                        },
                        new
                        {
                            Id = 4,
                            CoverImageUrl = "https://picsum.photos/seed/godofwar/300/400",
                            CreatedAt = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Kratos ve Atreus, Ragnarök'ü durdurmak için Dokuz Diyar'ı gezer. Epik bir baba-oğul hikayesi.",
                            Developer = "Santa Monica Studio",
                            Publisher = "Sony Interactive",
                            Rating = 4.7999999999999998,
                            ReleaseYear = 2022,
                            ReviewCount = 0,
                            Title = "God of War Ragnarök"
                        },
                        new
                        {
                            Id = 5,
                            CoverImageUrl = "https://picsum.photos/seed/hollowknight/300/400",
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Harap olmuş böcek krallığı Hallownest'te geçen 2D aksiyon macera. Zorlu ama ödüllendirici bir yolculuk.",
                            Developer = "Team Cherry",
                            Publisher = "Team Cherry",
                            Rating = 4.7000000000000002,
                            ReleaseYear = 2017,
                            ReviewCount = 0,
                            Title = "Hollow Knight"
                        },
                        new
                        {
                            Id = 6,
                            CoverImageUrl = "https://picsum.photos/seed/hades/300/400",
                            CreatedAt = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Olympus'a kaçmaya çalışan yeraltı tanrısı Zagreus'u oyna. Her ölümde daha güçlen.",
                            Developer = "Supergiant Games",
                            Publisher = "Supergiant Games",
                            Rating = 4.7999999999999998,
                            ReleaseYear = 2020,
                            ReviewCount = 0,
                            Title = "Hades"
                        },
                        new
                        {
                            Id = 7,
                            CoverImageUrl = "https://picsum.photos/seed/witcher3/300/400",
                            CreatedAt = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Geralt of Rivia olarak kızını ara, canavarlarla savaş. En iyi açık dünya RPG'lerinden biri.",
                            Developer = "CD Projekt Red",
                            Publisher = "CD Projekt",
                            Rating = 4.9000000000000004,
                            ReleaseYear = 2015,
                            ReviewCount = 0,
                            Title = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = 8,
                            CoverImageUrl = "https://picsum.photos/seed/rdr2/300/400",
                            CreatedAt = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Arthur Morgan olarak Amerika'nın dönüm noktasında hayatta kalmaya çalış. Muhteşem açık dünya.",
                            Developer = "Rockstar Games",
                            Publisher = "Rockstar Games",
                            Rating = 4.7999999999999998,
                            ReleaseYear = 2018,
                            ReviewCount = 0,
                            Title = "Red Dead Redemption 2"
                        },
                        new
                        {
                            Id = 9,
                            CoverImageUrl = "https://picsum.photos/seed/discoelysium/300/400",
                            CreatedAt = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Başarısız bir dedektif olarak şehri keşfet. Metin tabanlı kararların her şeyi değiştirir.",
                            Developer = "ZA/UM",
                            Publisher = "ZA/UM",
                            Rating = 4.5999999999999996,
                            ReleaseYear = 2019,
                            ReviewCount = 0,
                            Title = "Disco Elysium"
                        },
                        new
                        {
                            Id = 10,
                            CoverImageUrl = "https://picsum.photos/seed/civ6/300/400",
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Bir uygarlık kur ve tarih boyunca geliştir. Strateji türünün zirvesi.",
                            Developer = "Firaxis Games",
                            Publisher = "2K Games",
                            Rating = 4.5,
                            ReleaseYear = 2016,
                            ReviewCount = 0,
                            Title = "Sid Meier's Civilization VI"
                        });
                });

            modelBuilder.Entity("CheckpointAPI.Entities.GameGenre", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.HasKey("GameId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("GameGenres");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            GenreId = 1
                        },
                        new
                        {
                            GameId = 1,
                            GenreId = 2
                        },
                        new
                        {
                            GameId = 1,
                            GenreId = 6
                        },
                        new
                        {
                            GameId = 1,
                            GenreId = 4
                        },
                        new
                        {
                            GameId = 2,
                            GenreId = 1
                        },
                        new
                        {
                            GameId = 2,
                            GenreId = 2
                        },
                        new
                        {
                            GameId = 2,
                            GenreId = 5
                        },
                        new
                        {
                            GameId = 2,
                            GenreId = 4
                        },
                        new
                        {
                            GameId = 3,
                            GenreId = 1
                        },
                        new
                        {
                            GameId = 3,
                            GenreId = 5
                        },
                        new
                        {
                            GameId = 3,
                            GenreId = 4
                        },
                        new
                        {
                            GameId = 4,
                            GenreId = 2
                        },
                        new
                        {
                            GameId = 4,
                            GenreId = 3
                        },
                        new
                        {
                            GameId = 5,
                            GenreId = 2
                        },
                        new
                        {
                            GameId = 5,
                            GenreId = 7
                        },
                        new
                        {
                            GameId = 5,
                            GenreId = 3
                        },
                        new
                        {
                            GameId = 6,
                            GenreId = 2
                        },
                        new
                        {
                            GameId = 6,
                            GenreId = 8
                        },
                        new
                        {
                            GameId = 6,
                            GenreId = 7
                        },
                        new
                        {
                            GameId = 7,
                            GenreId = 1
                        },
                        new
                        {
                            GameId = 7,
                            GenreId = 4
                        },
                        new
                        {
                            GameId = 7,
                            GenreId = 6
                        },
                        new
                        {
                            GameId = 8,
                            GenreId = 2
                        },
                        new
                        {
                            GameId = 8,
                            GenreId = 3
                        },
                        new
                        {
                            GameId = 8,
                            GenreId = 4
                        },
                        new
                        {
                            GameId = 9,
                            GenreId = 1
                        },
                        new
                        {
                            GameId = 9,
                            GenreId = 3
                        },
                        new
                        {
                            GameId = 9,
                            GenreId = 7
                        },
                        new
                        {
                            GameId = 10,
                            GenreId = 10
                        });
                });

            modelBuilder.Entity("CheckpointAPI.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "RPG"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Open World"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Indie"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Rogue-like"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Racing"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Strategy"
                        });
                });

            modelBuilder.Entity("CheckpointAPI.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId", "GameId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("CheckpointAPI.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Bio")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CheckpointAPI.Entities.UserFollow", b =>
                {
                    b.Property<int>("FollowerId")
                        .HasColumnType("int");

                    b.Property<int>("FollowingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FollowedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("FollowerId", "FollowingId");

                    b.HasIndex("FollowingId");

                    b.ToTable("UserFollows");
                });

            modelBuilder.Entity("CheckpointAPI.Entities.UserLibrary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastPlayedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId", "GameId")
                        .IsUnique();

                    b.ToTable("UserLibraries");
                });

            modelBuilder.Entity("CheckpointAPI.Entities.Achievement", b =>
                {
                    b.HasOne("CheckpointAPI.Entities.User", "User")
                        .WithMany("Achievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CheckpointAPI.Entities.GameGenre", b =>
                {
                    b.HasOne("CheckpointAPI.Entities.Game", "Game")
                        .WithMany("GameGenres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CheckpointAPI.Entities.Genre", "Genre")
                        .WithMany("GameGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("CheckpointAPI.Entities.Review", b =>
                {
                    b.HasOne("CheckpointAPI.Entities.Game", "Game")
                        .WithMany("Reviews")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CheckpointAPI.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CheckpointAPI.Entities.UserFollow", b =>
                {
                    b.HasOne("CheckpointAPI.Entities.User", "Follower")
                        .WithMany()
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CheckpointAPI.Entities.User", "Following")
                        .WithMany()
                        .HasForeignKey("FollowingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Follower");

                    b.Navigation("Following");
                });

            modelBuilder.Entity("CheckpointAPI.Entities.UserLibrary", b =>
                {
                    b.HasOne("CheckpointAPI.Entities.Game", "Game")
                        .WithMany("LibraryEntries")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CheckpointAPI.Entities.User", "User")
                        .WithMany("LibraryEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CheckpointAPI.Entities.Game", b =>
                {
                    b.Navigation("GameGenres");

                    b.Navigation("LibraryEntries");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("CheckpointAPI.Entities.Genre", b =>
                {
                    b.Navigation("GameGenres");
                });

            modelBuilder.Entity("CheckpointAPI.Entities.User", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("LibraryEntries");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
